# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 445c2e9488ce852267a1a97757a9a1ea487d2130a64f95a853b0c81d15af133d5dfd7b8c738c76adf81887bcdeb149188af2c47deaffba7e030556ea3375e57f

test:
  secret_key_base: cbcad9d0b4599a044afad307aa2f749a34ba8640e76f965e4964a3b878dda08bc33d93ff82fcab904a74ab43af38da1df29b5b234278c892d4852a688690f9ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
